version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: <root password>
      MYSQL_USER: <user name>
      MYSQL_PASSWORD: <password>
      MYSQL_DATABASE: full-stack-ecommerce
    volumes:
      - ./:/docker-entrypoint-initdb.d
